name: Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # run it manually
  workflow_dispatch:

jobs:
  run:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      ### DEPENDENCIES ###

      # Hard turn-off interactive mode
      - run: echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections

      # Install qemu and binfmt
      - run: sudo apt update
      - run: sudo apt install --yes binfmt-support libpipeline1
      
      ### END DEPENDENCIES ###

      # Checkout git repository
      - uses: actions/checkout@v4
     
      # Setup KVM support
      - name: "KVM support"
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: set variable
        run: |
          echo "uname_m=$(uname -m)" >> $GITHUB_ENV

      - name: Install qemu static and set docker multiarch/qemu-user-static
        run: |
          cd ~ 
          curl -sL https://github.com/shengshampoo/qemu-static/releases/download/continuous/qemu-linux-${{ env.uname_m }}-10.2.0-chimera.tar.xz | tar x --xz 
          sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          sudo docker run -t --rm --platform=linux/arm64/v8 -v ~/qemu-linux-${{ env.uname_m }}-10.2.0/bin/qemu-aarch64:/usr/bin/qemu-aarch64-static arm64v8/alpine /bin/sh -c "uname -m && apk update && apk add neofetch --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing && neofetch"
          sudo docker run -t --rm --platform=linux/arm64/v8 -v ~/qemu-linux-${{ env.uname_m }}-10.2.0/bin/qemu-aarch64:/usr/bin/qemu-aarch64-static chimeralinux/chimera uname -a
          sudo docker run -t --rm --platform=linux/arm64/v8 -v ~/qemu-linux-${{ env.uname_m }}-10.2.0/bin/qemu-aarch64:/usr/bin/qemu-aarch64-static bellsoft/alpaquita-linux-base:stream-musl uname -a
             
